In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
n = 5

x_test = np.linspace(start=0, stop=1, num=n)
print(x_test)
x_train = np.array([0.25, 0.5, 0.75])
y_train = x_train


def covariance(x1, x2):
    #return (x1 * x2)
    #return np.exp(-0.5 * (x1 - x2)**2)
    return np.exp(-(2 * np.sin(np.pi * (x1 - x2)**2)))

def generate_covariance_matrix(x,y):

    n1 = x.shape[0]
    n2 = y.shape[0]


    covariance_matrix = np.zeros((n1,n2))

    for i in range(n1):
        for j in range(n2):
            covariance_matrix[i][j] = covariance(x[i], y[j])
            
        

    return covariance_matrix


K_test_train = generate_covariance_matrix(x_test, x_train)
K_train_test = generate_covariance_matrix(x_train, x_test)
K_test_test = generate_covariance_matrix(x_test, x_test)
K_train_train  = generate_covariance_matrix(x_train, x_train)

mu = np.zeros(n)
covariance_matrix = generate_covariance_matrix(x_test, x_test)
#mu = K_test_train.dot(np.linalg.inv(K_train_train)).dot(x_train)
#covariance_matrix = K_test_test - K_test_train.dot(np.linalg.inv(K_train_train)).dot(K_train_test)


print(covariance_matrix)

def multivariate_guassian(mu, covariance_matrix):
    u = np.random.normal(loc=0, scale=0.01, size=mu.shape[0])
    #covariance_matrix = covariance_matrix + np.diag(np.random.normal(loc=0, scale=1, size=covariance_matrix.shape[0]))
    print(covariance_matrix)
    print(np.linalg.eigvalsh(covariance_matrix))
    L = np.linalg.cholesky(covariance_matrix)
    return mu + np.matmul(L, u)


y_test = multivariate_guassian(mu, covariance_matrix)

x=x_test
y=y_test
# x = x_test + x_train
# y = y_test + y_train

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

sns.heatmap(ax=axes[0], data=covariance_matrix)
axes[0].set_title("Covariance Matrix")

axes[1].set_title("Sample Function")
axes[1].scatter(x, y)



[0.   0.25 0.5  0.75 1.  ]
[[1.         0.67693458 0.24311673 0.14063737 1.        ]
 [0.67693458 1.         0.67693458 0.24311673 0.14063737]
 [0.24311673 0.67693458 1.         0.67693458 0.24311673]
 [0.14063737 0.24311673 0.67693458 1.         0.67693458]
 [1.         0.14063737 0.24311673 0.67693458 1.        ]]
[[1.         0.67693458 0.24311673 0.14063737 1.        ]
 [0.67693458 1.         0.67693458 0.24311673 0.14063737]
 [0.24311673 0.67693458 1.         0.67693458 0.24311673]
 [0.14063737 0.24311673 0.67693458 1.         0.67693458]
 [1.         0.14063737 0.24311673 0.67693458 1.        ]]
[-0.27793689  0.10467507  1.03482016  1.23938197  2.8990597 ]


LinAlgError: Matrix is not positive definite

In [66]:
np.array([0.25,0.5,0.75])

    

array([0.25, 0.5 , 0.75])

In [68]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
A = np.array([[1,2,3],[2,4,6]])
B = np.array([[2,3],[3,4],[5,6]])
print(A.dot(B))

[[23 29]
 [46 58]]
